### ISSUE TITLE
Add turbolinks example

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#1]
**Context**
- In Turbolinks (e.g., Github), navigation event occurs before page content changes
- This can be modeled with multiple static pages. We don't need to have a backend
- We _might_ need/want to add a delay to the page load in order to make reproducing the effect more consistent

**Implementation Sketch**
- Create a new "turbolinks" folder
- Add a few files HTML files that include the following packages via CDN
  - Turbolinks: https://www.jsdelivr.com/package/npm/turbolinks
  - Bootstrap 5
- Page Structure:
  - Navbar: persisted across page loads: https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads
  - Body with some example content on each page: 1) Landing Page, 2) Form, 3) Dashboard. You can use the example content from here: https://getbootstrap.com/docs/5.0/examples/

**Other Notes**
- For local development you might need to serve the side via a HTTP server (for example with Python: `python3 -m http.server 8001`) for Turbolinks loading to work correctly. (JS/Node also probably has support for serving files in a directory)

**Comment by fregante** [comment]
Done in https://github.com/pixiebrix/playground/pull/30
