### ISSUE TITLE
Add vue admin example

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#16]
Context
* https://github.com/PanJiaChen/vue-element-admin is a project that's an admin panel showcase that doesn't require a backend
* It looks like out of the box we don't need a backend for it since all of its network requests are mocked
* Instead of copying the code to our repository, let's clone a release from their repository?

Implementation Sketch
* Create a folder vue-element-admin
* Add project with a build: https://github.com/pixiebrix/playground#adding-a-project-with-a-build
* In the directory, add a build script with the steps:
  * Clone the repository
  * Apply a patch (if needed) using `git apply`
  * https://github.com/PanJiaChen/vue-element-admin#getting-started
  * Do a production build: https://github.com/PanJiaChen/vue-element-admin#build
* Submit a PR, and verify the application is working in the PR demo deploy

Considerations
* When cloning the repository during the build, do a shallow clone so the clone is fast

**Comment by twschiller** [comment]
@fregante do these instructions make sense? It probably doesn't make sense to copy the code over to our repository

We have someone who's going to be helping us add examples to this repository

**Comment by fregante** [comment]
The advantage of publishing something ourselves is that things don't change unless we want them to. This means we can safely use the playground for automated tests.

If we just want something to play with occasionally, we can just add a link to external projects instead, knowing they might change over time (but at least we don't spend time setting a project up)

**Comment by twschiller** [comment]
> The advantage of publishing something ourselves is that things don't change unless we want them to. This means we can safely use the playground for automated tests.

I think a good compromise is to clone a specific release/commit from the project. And in our repository we can keep a patch/diff to apply to that version of the external project

The build looks like:
1. Check out / clone
2. Apply diff / patch
3. Run the projects build steps

We'd also add the cloned project directories to the .gitignore

@fregante see any downsides with the diff/patch method?

**Comment by fregante** [comment]
I suppose it's a good way to keep this repo light, but I think it will be difficult to maintain that patch manually. I don't feel strongly about it though.

**Comment by twschiller** [comment]
> I suppose it's a good way to keep this repo light, but I think it will be difficult to maintain that patch manually. I don't feel strongly about it though.

For projects were we need them stable but don't need to make any/many changes let's try the clone and patch approach for now

We might also consider submodules? (I haven't tried them before: https://stackoverflow.com/a/5205785/402560)

**Comment by fregante** [comment]
> We might also consider submodules

I heard that they're not well-liked, but since we don't have to make changes across repositories it might not be that bad. Essentially the difference between the manual clone/checkout vs submodules is that the latter is probably automatically managed by the first `git checkout`
