### ISSUE TITLE
Add site with Hotkeys via document listener

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#2]
**Context**
- Sites with hotkeys often attach a document listener that capture key events on the bubble
- They perform event filtering to determine whether or not to trigger the hotkey (e.g., they won't trigger a hotkey if the user is editing something). 
- Currently we can't do anything about this b/c we run our content script on idle. The approach we've taken instead is to embed out content in iframes so the host page doesn't get an event

**Comment by fregante** [comment]
I assume this is related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/1865

> * Currently we can't do anything about this

What is the issue exactly? What happens when a website has hotkeys? Is it because the user cannot override those specifically or does it break _all_ of our hot keys?

**Comment by twschiller** [comment]
> What is the issue exactly? What happens when a website has hotkeys? Is it because the user cannot override those specifically or does it break all of our hot keys?

What we've seen sites do is install their Hotkey handler on the `document` with some additional logic for to ignore the keypress combination (e.g., if a field is currently in edit mode, which is determined by CSS classes and DOM structure)

So the document handler gets the keypress/down event, handles it, and then cancels the propagation

What this means for us is:
* The user wouldn't be able to override hotkeys,
* We can't reliably prevent hotkeys from triggering while the user is interacting with a PixieBrix page element. E.g., the hotkey would trigger while a user was typing into our form modal before we moved it to an iframe

So in order for us to override a hotkey (or prevent the hotkey while a PixieBrix element has focus) we'd need to add our handler before the host page does (by adding the handler at document begin)
