### ISSUE TITLE
vue-element-admin route cleanup

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#27]
Context
- See: https://github.com/pixiebrix/playground/pull/26#issuecomment-991511217

Implementation Sketch
- Remove unused entry from vercel.json

**Comment by fregante** [comment]
No that commit I mentioned is already on the main branch now, it has already been cleaned up

**Comment by twschiller** [comment]
> No that commit I mentioned is already on the main branch now, it has already been cleaned up

Awesome, thanks!
