### ISSUE TITLE
Add infinite scroll example

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/playground#3]
**Context**
- Infinite scroll requires an extension point to continuous look for new elements to attach elements (e.g., menu items to)

**Implementation Sketch**
- Create a directory called infinite scroll
- Create a page with this library: https://infinite-scroll.com/

**Comment by fregante** [comment]
@EmmanuelObua when creating PRs you can include "Fixes #3" and GitHub will automatically close these issues, as well as link your PR to the requested change.
