### ISSUE TITLE
Rethink deployment strategy

### ISSUE THREAD

**Issue by fregante** [pixiebrix/playground#31]
We're only 6 projects in and the build is already taking 20 minutes 😰  https://vercel.com/pixiebrix/playground/G3rW9PbY9Y3ihbBrcGBgxAt2VjYJ

We should probably fix this before Vercel just stops building (and because 20 minutes is already a long time to find out whether something worked).

I don't know how to fix this yet, but I think it should **only build a project if it was changed.**

Possible solutions:

- https://turborepo.org/docs/getting-started (Vercel just bought this)
- Build on GitHub Actions (easier to skip parts of a build, needs some work to get PR preview builds)
- Ensure that Vercel’s build cache is working

Thoughts? We could also just use a regular host/S3/EC2, but preview builds and lack of server maintenance are a big plus for Vercel.

I sent a message to Vercel hoping for suggestions.

Platform limits:

- https://vercel.com/docs/concepts/deployments/build-step#technical-details

**Comment by twschiller** [comment]
Thanks for pointing this out! Having a long build definitely defeats part of the purpose of the repository

Other options/ideas:
- Have developers check-in the front-ends into the repo. Downside: reproducibility
- To build on the Github Actions idea, have a separate branch that GitHub actions deploys the static files to that branch. That branch gets deployed to Vercel. Downside: would have to get creative with how PRs work
- Without turborepo, can you set up separate projects on vercel for the same repository?
