### ISSUE TITLE
`advanced-fields` issues

### ISSUE THREAD

**Issue by fregante** [pixiebrix/playground#48]
- [ ] TinyMCE 6: readonly due to missing api key

https://github.com/pixiebrix/playground/blob/08fa0bffba4216caf73e9d1b2fd5ca7757ff0243/static/advanced-fields/index.html#L115

**Comment by twschiller** [comment]
@fregante I sent over an API key

**Comment by fregante** [comment]
> You can find example HTML on your account dashboard with your API key already inserted in the script. Copy the code directly from there to create an HTML file hosted on your server.

I can't find any examples of where to place the API in our code, can you paste what they give you in their dashboard?

**Comment by twschiller** [comment]
You throw it in the URL for the script: `<script src="https://cdn.tiny.cloud/1/<APIKEY>/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>`

**Comment by fregante** [comment]
![](https://github.com/pixiebrix/playground/assets/1402241/1cc7327c-3591-4841-8151-0c03c09059ec)
