### ISSUE TITLE
Use subdomain like playground.pixiebrix.com?

### ISSUE THREAD

**Issue by fregante** [pixiebrix/playground#5]
We can configure GitHub Pages to be available on a custom address, we just need a to point a subdomain GitHub and configure it in this repo’s settings tab.

## Before

https://pixiebrix.github.io/playground/example/

## After

https://playground.pixiebrix.com/example

**Comment by twschiller** [comment]
Thinking more about this, I want to keep it on a separate subdomain so cookies/extensions/password managers don't treat it like it's on the pixiebrix domain

**Comment by fregante** [comment]
> I want to keep it on a separate subdomain so cookies/extensions/password managers don't treat it like it's on the pixiebrix domain.

Yes indeed! `pixiebrix.com` is also included in the manifest so it wouldn't work the same as a proper "third party website"



> Were there benefits to hosting on the subdomain aside from a bit better branding?

Small stuff: Having a shorter URL is just a little better for everything (faster to visually parse, less chance of wrapping) but we'd have the most benefits only if we managed to map a sub-folder to a subdomain automatically, e.g. `example.pixiebrix.vercel.app`, `react-example.pixiebrix.vercel.app`, because we'd then have a host for each example, and they'll all be served from "root"

Maybe not worth it though

**Comment by fregante** [comment]
By the way, a simple improvement here would be to rename this repo to `pixiebrix.github.io` so that GitHub will serve it as:

```
https://pixiebrix.github.io/react-example
```

instead of

```
https://pixiebrix.github.io/playground/react-example
```

**Comment by twschiller** [comment]
> By the way, a simple improvement here would be to rename this repo to pixiebrix.github.io so that GitHub will serve it as

Thanks for the suggestion. I'd prefer not to pollute our root namespace

If name length becomes a problem, we'll grab a `.dev` domain and throw things on vecel, S3 or somewhere else. Let's revisit if/when we start hitting name length issues
